Repository Chia-Network/chia-blockchain-gui, pull requests merged in 2022-12, with the labels that each got.

#1213 Display current NFT coin ID and p2 address on the details screen
  packages/api/src/@types/NFTInfo.ts
  packages/gui/src/components/nfts/NFTDetails.tsx
Labels: Added

#1223 fix exception in NFTDetails.tsx (currencyCode needs to be defined)
  packages/gui/src/components/nfts/NFTDetails.tsx
Labels: Fixed

#1235 Updated wording for the allowConfirmationFingerprintChange setting
  packages/gui/src/components/settings/SettingsIntegration.tsx
Labels: Fixed

#1237 Update eslint rules
  .eslintrc.json
Labels: Changed

#1240 checkpoint: into main from release/1.7.0 @ 87d3cf11cff87ae074c952327e2112c48e7e4cd5
  packages/gui/src/hooks/useWalletConnect.ts
  packages/gui/src/hooks/useWalletConnectCommand.tsx
  packages/gui/src/util/walletConnect.ts
Labels: Changed

#1241 checkpoint: into main from release/1.7.0 @ 46d871c5aad2aca0df081ef94c7a4b474dce84bc
  packages/gui/src/components/settings/SettingsIntegration.tsx
Labels: Changed

#1253 Bump Electron to 20.3.8
  packages/core/package-lock.json
  packages/core/package.json
  packages/gui/package-lock.json
  packages/gui/package.json
Labels: Changed

#1255 Rename "Wallet Connect" --> "WalletConnect"
  packages/gui/src/components/settings/SettingsIntegration.tsx
  packages/gui/src/components/walletConnect/WalletConnectAddConnectionDialog.tsx
  packages/gui/src/components/walletConnect/WalletConnectConnectedDialog.tsx
  packages/gui/src/components/walletConnect/WalletConnectConnections.tsx
  packages/gui/src/util/walletConnect.ts
Labels: Changed

#1257 Refactor NFT metadata LRU implementation
  packages/core/src/utils/index.ts
  packages/core/src/utils/lru.test.ts
  packages/core/src/utils/lru.ts
  packages/gui/src/components/app/AppProviders.tsx
  packages/gui/src/components/lrus/LRUsProvider.tsx
  packages/gui/src/components/nfts/NFTContextualActions.tsx
  packages/gui/src/hooks/useAllowFilteredShow.tsx
  packages/gui/src/hooks/useNFTMetadata.ts
  packages/gui/src/hooks/useNFTMetadataLRU.ts
Labels: Changed
