Repository Chia-Network/chia-blockchain-gui, pull requests merged in 2023-10, with the labels that each got.

#2186 checkpoint: into main from release/2.1.0 @ b2ce40bc41bcceedaee887fc059466486b2e09bc
  packages/core/src/components/EstimatedFee/EstimatedFee.tsx
Labels: Changed, checkpoint_merge

#2192 Downgrade electron to 25.9.0
  package-lock.json
  packages/core/package.json
  packages/gui/package.json
Labels: Fixed

#2196 Hide compression option if bladebit version < 3
  packages/gui/src/components/plot/add/PlotAddChooseSize.tsx
  packages/gui/src/components/plot/add/PlotAddForm.tsx
Labels: Fixed

#2199 Fixed add plot directory button
  packages/gui/src/components/plot/PlotAddDirectoryDialog.tsx
  packages/gui/src/components/plot/overview/PlotOverviewPlots.tsx
Labels: Fixed

#2211 Added `insufficient_partials` stat item on farm page
  packages/api/src/@types/PoolState.ts
  packages/api/src/services/Farmer.ts
  packages/gui/src/components/farm/PoolingHealth.tsx
Labels: Changed
