Repository Chia-Network/chia-blockchain-gui, pull requests merged in 2023-09, with the labels that each got.

#2062 Fixed effective plot size values
  packages/gui/src/constants/plotSizes.ts
Labels: Fixed

#2061 Removed `-no-direct_downloads` option from bladebit
  packages/api/src/@types/Plotter.ts
  packages/api/src/constants/Plotters.ts
  packages/api/src/services/Daemon.ts
  packages/gui/src/components/plot/add/PlotAddNumberOfPlots.tsx
  packages/gui/src/types/PlotAdd.ts
  packages/gui/src/types/Plotter.ts
Labels: Fixed

#2087 Fixed an issue where expected average passed filter count was wrong
  packages/gui/src/components/harvest/HarvesterOverview.tsx
Labels: Fixed

#2094 checkpoint: into main from release/2.1.0 @ b52e6587be0e1b8daa4b48f38d8fa6c8d741b0bb
  .github/workflows/audit.yml
  .github/workflows/crowdin-pull.yml
  .github/workflows/crowdin-push.yml
  .github/workflows/extract-strings.yml
Labels: Changed, checkpoint_merge

#2100 checkpoint: into main from release/2.1.0 @ d8e44c860fc653ce3716e8212f484f386b4038c2
  .github/workflows/crowdin-pull.yml
Labels: Changed, checkpoint_merge

#2102 checkpoint: into main from release/2.1.0 @ cb9ecd310ee54ab398a8f268622fbb55e141756f
  .github/workflows/crowdin-pull.yml
Labels: Changed, checkpoint_merge

#2110 checkpoint: into main from release/2.1.0 @ 5b0748a93cd1b737108ad92193cf42788f8eb6b7
  .github/workflows/crowdin-pull.yml
Labels: Changed, checkpoint_merge

#2118 Removed compression level 0 from the cuda plot option
  packages/api/src/constants/Plotters.ts
  packages/gui/src/components/plot/add/PlotAddChooseSize.tsx
Labels: Fixed

#2119 checkpoint: into main from release/2.1.0 @ fbbc554eb72f838573356f8fe00912a286388e05
  packages/api-react/src/hooks/useService.ts
  packages/api-react/src/hooks/useServices.ts
Labels: Changed, checkpoint_merge

#2117 Fixed an issue where status indicators always show `NOT RUNNING`
  packages/gui/src/components/farm/FarmFullNodeConnections.tsx
  packages/gui/src/components/farm/FarmYourHarvesterNetwork.tsx
  packages/gui/src/components/fullNode/card/FullNodeCardConnectionStatus.tsx
  packages/gui/src/hooks/useFarmerStatus.ts
  packages/gui/src/hooks/useIsServiceRunning.ts
Labels: Fixed

#2120 checkpoint: into main from release/2.1.0 @ f6a1bfc1d0b0fab3b46c55a87f60d818461809ea
  packages/gui/src/components/offers2/OfferBuilderExpirationSection.tsx
Labels: Changed, checkpoint_merge

#2128 checkpoint: into main from release/2.1.0 @ 74e0ea52c8e50ab2af57aa1ace2577c0d7a601ae
  packages/api/src/constants/Plotters.ts
  packages/gui/src/components/plot/add/PlotAddChooseSize.tsx
Labels: Changed, checkpoint_merge

#2135 checkpoint: into main from release/2.1.0 @ 2662786f56969ff5a4babbe3019ec0cdcacdc3ae
  packages/gui/src/components/farm/FarmFullNodeConnections.tsx
  packages/gui/src/components/farm/FarmYourHarvesterNetwork.tsx
  packages/gui/src/components/fullNode/card/FullNodeCardConnectionStatus.tsx
  packages/gui/src/hooks/useFarmerStatus.ts
  packages/gui/src/hooks/useIsServiceRunning.ts
Labels: Changed, checkpoint_merge

#2136 checkpoint: into main from release/2.1.0 @ 75d0a6c89b7c841d6a2d7471a7135e659ca9e3ae
  packages/api/src/@types/index.ts
  packages/gui/src/components/offers/OfferManager.tsx
  packages/gui/src/components/offers2/OfferBuilderExpirationSection.tsx
  packages/gui/src/components/offers2/OfferBuilderHeader.tsx
  packages/gui/src/components/offers2/OfferBuilderSection.tsx
  packages/gui/src/components/offers2/OfferBuilderTradeColumn.tsx
  packages/gui/src/components/offers2/OfferBuilderViewer.tsx
  packages/gui/src/components/plotNFT/PlotExternalNFTCard.tsx
  packages/wallets/src/components/ClawbackClaimTransactionDialog.tsx
  packages/wallets/src/components/WalletHistoryClawbackChip.tsx
Labels: Changed, checkpoint_merge

#2137 checkpoint: into main from release/2.1.0 @ a602be6f9f5ac2eb0cde3b49d47b7c21aed67b86
  packages/gui/package.json
Labels: Changed, checkpoint_merge

#2138 checkpoint: into main from release/2.1.0 @ ec7cfcc8f93865e95927627a50ea59d7756c44d1
  packages/gui/src/components/offers2/CreateOfferBuilder.tsx
Labels: Changed, checkpoint_merge

#2141 checkpoint: into main from release/2.1.0 @ 4b1e27161f1df84d39996b669fc2abd6a66860c7
  packages/gui/src/components/app/AppStatusHeader.tsx
  packages/gui/src/components/app/AppTestnetIndicator.tsx
  packages/gui/src/components/app/LogoutButton.tsx
  packages/gui/src/components/notification/NotificationsDropdown.tsx
  packages/gui/src/components/walletConnect/WalletConnectDropdown.tsx
Labels: Changed, checkpoint_merge

#2144 checkpoint: into main from release/2.1.0 @ bc3c7a971a10929fe9b98c623b405ddf730b8b7a
  packages/gui/src/components/settings/SettingsHarvester.tsx
Labels: Changed, checkpoint_merge

#2143 Fixed farm page crash
  packages/api/src/@types/BlockchainState.ts
  packages/gui/src/components/farm/FarmHealth.tsx
Labels: Fixed

#2147 checkpoint: into main from release/2.1.0 @ e087cfe32b9c356819643262ac5737f5a3dfa46e
  packages/core/src/theme/dark.ts
  packages/core/src/theme/default.ts
Labels: Changed, checkpoint_merge

#2148 checkpoint: into main from release/2.1.0 @ 9b6b8ee76a4d1677d2c4f989f373abed64645a9a
  packages/api/src/@types/BlockchainState.ts
  packages/gui/src/components/farm/FarmHealth.tsx
Labels: Changed, checkpoint_merge

#2156 checkpoint: into main from release/2.1.0 @ c1e50a287c0fc71f1ef07a152eb49276ee0d3200
  packages/gui/src/components/plot/add/PlotAddSelectHybridDiskMode.tsx
Labels: Changed, checkpoint_merge

#2158 Added a warning dialog appeared when selecting hybrid 128G mode
  packages/gui/src/components/plot/add/PlotAddSelectHybridDiskMode.tsx
Labels: Added

#2159 checkpoint: into main from release/2.1.0 @ 07fa8ada0df8d80239b24bd9294c50d0542c57a0
  packages/gui/src/components/plot/add/PlotAddSelectHybridDiskMode.tsx
Labels: Changed, checkpoint_merge

#2169 checkpoint: into main from release/2.1.0 @ 11113bef48ad8f391d08d10b0cc665e07c3c58be
  packages/core/src/components/LayoutDashboard/LayoutDashboard.tsx
Labels: Changed, checkpoint_merge

#2170 checkpoint: into main from release/2.1.0 @ b493bda66f32e4dcf8970eb172c9369aff7efcbc
  packages/gui/src/constants/WalletConnectCommands.tsx
Labels: Changed, checkpoint_merge

#2171 checkpoint: into main from release/2.1.0 @ 7e9b5a19755fb58f632efb94fb5cd73eae103e81
  packages/gui/src/components/nfts/NFTCard.tsx
  packages/gui/src/components/offers2/OfferBuilderExpirationSection.tsx
  packages/icons/src/Hourglass.tsx
  packages/icons/src/images/Hourglass.svg
  packages/icons/src/index.ts
Labels: Changed, checkpoint_merge

#2172 checkpoint: into main from release/2.1.0 @ ef10761cc0f60d275dbd0895c59729eed081aad1
  packages/core/src/screens/SelectKey/SelectKeyItem.tsx
Labels: Changed, checkpoint_merge

#2179 checkpoint: into main from release/2.1.0 @ 642650aab61e132bc14c828140ac6dbd0f92e1d7
  packages/core/src/screens/SelectKey/EmojiAndColorPicker.tsx
  packages/gui/src/components/offers2/OfferBuilderExpirationSection.tsx
  packages/gui/src/components/offers2/OfferBuilderViewer.tsx
  packages/gui/src/components/settings/SettingsExpiringOffers.tsx
Labels: Changed, checkpoint_merge
