Repository Chia-Network/chia-blockchain-gui, pull requests merged in 2023-12, with the labels that each got.

#2237 checkpoint: into main from release/2.1.2 @ fc448a5156fd526da5d6ecf049c133f0b216caaf
  packages/gui/package.json
Labels: Changed, checkpoint_merge

#2238 checkpoint: into main from release/2.1.2 @ 2d1e0518a48677dff4aed10986bb1be2ca151581
  packages/gui/package.json
Labels: Changed, checkpoint_merge

#670 Added checkbox for keeping service running background after GUI closes
  packages/gui/src/electron/main.tsx
Labels: enhancement, PR ready

#2246 Fixed a possible plotting issue
  packages/gui/src/components/plot/add/PlotAddForm.tsx
Labels: bug
