Repository Chia-Network/chia-blockchain-gui, pull requests merged in 2023-01, with the labels that each got.

#1273 Clear gallery NFT cache on disk (settings button)
  packages/gui/src/components/settings/SettingsNFT.tsx
  packages/gui/src/electron/main.tsx
Labels: Added

#1281 Update version check to account for '+' (PEP440 local version)
  packages/gui/src/components/app/AppState.tsx
Labels: Changed

#1292 Fix metadata cache retrieval from local storage
  packages/gui/src/hooks/useNFTMetadata.ts
Labels: Fixed

#1284 Add 12-word mnemonic import option
  packages/core/src/screens/SelectKey/SelectKey.tsx
  packages/wallets/src/components/PasteMnemonic.tsx
  packages/wallets/src/components/WalletImport.tsx
Labels: Added

#1354 prevent an infinite loop calling check_offer_validity
  packages/gui/src/components/offers2/OfferBuilderViewer.tsx
Labels: Fixed

#1389 checkpoint: into main from release/1.7.0 @ 46ed96960b3ece43ab5b13b17fdd61446b703228
  packages/api-react/src/services/index.ts
  packages/api-react/src/services/wallet.ts
  packages/api/src/services/Service.ts
  packages/api/src/services/WalletService.ts
  packages/core/src/components/LayoutDashboard/LayoutDashboard.tsx
  packages/core/src/screens/SelectKey/SelectKey.tsx
  packages/gui/src/components/helpers/HeightToTimestamp.tsx
  packages/gui/src/components/notification/Notification.tsx
  packages/gui/src/components/notification/NotificationSendDialog.tsx
  packages/gui/src/components/notification/NotificationsDropdown.tsx
  packages/gui/src/components/offers/OfferManager.tsx
  packages/gui/src/components/offers/OfferShareDialog.tsx
  packages/gui/src/components/offers2/CreateOfferBuilder.tsx
  packages/gui/src/components/offers2/OfferIncomingTable.tsx
  packages/gui/src/components/settings/SettingsNotifications.tsx
  packages/gui/src/constants/NotificationType.ts
  packages/gui/src/constants/OfferServices.ts
  packages/gui/src/hooks/useNotifications.tsx
  packages/gui/src/util/fetchOffer.ts
  packages/gui/src/util/parseNotification.ts
Labels: Changed

#1394 checkpoint: into main from release/1.7.0 @ c9d7b13a3e1a7a958d086e46f5d590d18f876b2d
  packages/core/src/components/ModalDialogs/ModalDialogsProvider.tsx
Labels: Changed
