Repository Chia-Network/chia-blockchain-gui, pull requests merged in 2023-02, with the labels that each got.

#1414 checkpoint: into main from release/1.7.0 @ 10c03305062e486d0da26fb8edeb42754e1a7f42
  packages/gui/src/components/nfts/NFTProperties.tsx
  packages/gui/src/components/nfts/NFTRankings.tsx
Labels: Changed

#1420 checkpoint: into main from release/1.7.0 @ e3a084ef2d48df31045b23c428c6b1e4d81ed5cf
  packages/gui/src/components/settings/SettingsNotifications.tsx
Labels: Changed

#1424 checkpoint: into main from release/1.7.0 @ 21f58e03e637fee14cdf8b5d5b48c90843547056
  packages/gui/src/components/offers/OfferShareDialog.tsx
Labels: Changed

#1425 checkpoint: into main from release/1.7.0 @ aca8362551f659b2162a6c759bfc303389cb1f54
  packages/gui/src/components/offers/NFTOfferViewer.tsx
  packages/gui/src/components/offers/OfferShareDialog.tsx
Labels: Changed

#1429 checkpoint: into main from release/1.7.0 @ 4812bf4ac8e67f0f635fbf991939aa781b65effa
  packages/gui/src/components/plotNFT/PlotNFTUnconfirmedCard.tsx
Labels: Changed

#1430 checkpoint: into main from release/1.7.0 @ ac84d3b52f10eeebf743e39060c9d1fd22dec574
  packages/gui/src/components/settings/SettingsProfiles.tsx
Labels: Changed

#1431 checkpoint: into main from release/1.7.0 @ 89b86ecac984ffc883176b7d7b4cf58992f096dc
  packages/gui/src/components/app/AppStatusHeader.tsx
  packages/gui/src/components/notification/NotificationsDropdown.tsx
  packages/gui/src/components/walletConnect/WalletConnectDropdown.tsx
  packages/wallets/src/components/WalletReceiveAddressField.tsx
Labels: Changed

#1432 checkpoint: into main from release/1.7.0 @ bd5ca95ddc3f7c9d527713944721e09fbc253820
  packages/api-react/src/hooks/useCurrentFingerprintSettings.ts
  packages/api-react/src/hooks/useFingerprintSettings.ts
  packages/api-react/src/hooks/useLocalStorage.ts
  packages/api-react/src/hooks/usePrefs.ts
  packages/gui/src/components/app/AppProviders.tsx
  packages/gui/src/components/notification/Notification.tsx
  packages/gui/src/components/notification/NotificationsProvider.tsx
  packages/gui/src/electron/main.tsx
  packages/gui/src/hooks/useNotifications.tsx
  packages/gui/src/hooks/useShowNotification.ts
  packages/gui/src/util/fetchOffer.ts
  packages/icons/src/Offers.tsx
  packages/icons/src/images/Offers.svg
Labels: Changed

#1434 checkpoint: into main from release/1.7.0 @ a16cc97c65acb2b9307cf67f8ce705cd835a38ae
  packages/wallets/src/components/WalletHistory.tsx
Labels: Changed

#913 Enable code scanning
  .github/workflows/dependency-review.yml
Labels: stale-pr

#1267 Support for signing/verifying messages via wallet address | NFT | DID
  package-lock.json
  packages/api-react/src/services/index.ts
  packages/api-react/src/services/wallet.ts
  packages/api/src/services/WalletService.ts
  packages/api/src/utils/index.ts
  packages/api/src/wallets/DID.ts
  packages/gui/src/components/did/DIDProfileDropdown.tsx
  packages/gui/src/components/nfts/NFTMoveToProfileDialog.tsx
  packages/gui/src/components/offers2/OfferBuilderImport.tsx
  packages/gui/src/components/settings/SettingsAdvanced.tsx
  packages/gui/src/components/signVerify/SignMessage.tsx
  packages/gui/src/components/signVerify/SignMessageEntities.ts
  packages/gui/src/components/signVerify/SignMessageResultDialog.tsx
  packages/gui/src/components/signVerify/SignVerifyDialog.tsx
  packages/gui/src/components/signVerify/SigningEntityDID.tsx
  packages/gui/src/components/signVerify/SigningEntityNFT.tsx
  packages/gui/src/components/signVerify/SigningEntityWalletAddress.tsx
  packages/gui/src/components/signVerify/VerifyMessage.tsx
  packages/gui/src/components/signVerify/VerifyMessageImport.tsx
  packages/gui/src/hooks/usePaste.ts
  packages/gui/src/hooks/useSaveFile.ts
  packages/gui/src/util/utils.js
Labels: Added
