Repository Chia-Network/chia-blockchain-gui, pull requests merged in 2024-06, with the labels that each got.

#2360 Bump lerna to 8.1.3, ejs to 3.1.10
  package-lock.json
  package.json
Labels: dependencies

#2397 Bump react-hotkeys-hook to 4.5.0
  package-lock.json
  packages/core/package.json
  packages/gui/package.json
  packages/gui/src/components/offers/OfferImport.tsx
  packages/gui/src/components/offers2/OfferBuilderImport.tsx
  packages/gui/src/hooks/usePaste.ts
  packages/wallets/package.json
Labels: Fixed

#2412 checkpoint: into main from release/2.4.0 @ 4e2c293b954a517a9d91de66b5fa8fc248c7b889
  package-lock.json
  packages/core/package.json
  packages/gui/package.json
Labels: Changed, checkpoint_merge

#2415 Upgraded ws to 8.17.1 and solved some issues
  package-lock.json
  packages/gui/package.json
  packages/gui/webpack.react.babel.ts
Labels: dependencies
