Repository Chia-Network/chia-blockchain-gui, pull requests merged in 2024-10, with the labels that each got.

#2502 Fixed a mouse clicking issue
  packages/core/src/components/Button/Button.tsx
  packages/core/src/components/Link/Link.tsx
  packages/core/src/components/MenuItem/MenuItem.tsx
  packages/gui/src/components/notification/NotificationAnnouncementDialog.tsx
  packages/gui/src/electron/main.tsx
  packages/gui/src/hooks/useOpenUnsafeLink.tsx
  packages/gui/src/locales/ar-SA/messages.po
  packages/gui/src/locales/be-BY/messages.po
  packages/gui/src/locales/bg-BG/messages.po
  packages/gui/src/locales/ca-ES/messages.po
  packages/gui/src/locales/cs-CZ/messages.po
  packages/gui/src/locales/da-DK/messages.po
  packages/gui/src/locales/de-DE/messages.po
  packages/gui/src/locales/el-GR/messages.po
  packages/gui/src/locales/en-AU/messages.po
  packages/gui/src/locales/en-NZ/messages.po
  packages/gui/src/locales/en-PT/messages.po
  packages/gui/src/locales/en-US/messages.po
  packages/gui/src/locales/es-AR/messages.po
  packages/gui/src/locales/es-ES/messages.po
  packages/gui/src/locales/es-MX/messages.po
  packages/gui/src/locales/fa-IR/messages.po
  packages/gui/src/locales/fi-FI/messages.po
  packages/gui/src/locales/fr-FR/messages.po
  packages/gui/src/locales/hr-HR/messages.po
  packages/gui/src/locales/hu-HU/messages.po
  packages/gui/src/locales/id-ID/messages.po
  packages/gui/src/locales/it-IT/messages.po
  packages/gui/src/locales/ja-JP/messages.po
  packages/gui/src/locales/ko-KR/messages.po
  packages/gui/src/locales/nl-NL/messages.po
  packages/gui/src/locales/no-NO/messages.po
  packages/gui/src/locales/pl-PL/messages.po
  packages/gui/src/locales/pt-BR/messages.po
  packages/gui/src/locales/pt-PT/messages.po
  packages/gui/src/locales/ro-RO/messages.po
  packages/gui/src/locales/ru-RU/messages.po
  packages/gui/src/locales/sk-SK/messages.po
  packages/gui/src/locales/sq-AL/messages.po
  packages/gui/src/locales/sr-SP/messages.po
  packages/gui/src/locales/sv-SE/messages.po
  packages/gui/src/locales/tr-TR/messages.po
  packages/gui/src/locales/uk-UA/messages.po
  packages/gui/src/locales/zh-CN/messages.po
  packages/gui/src/locales/zh-TW/messages.po
Labels: Fixed

#2503 Updated label
  packages/gui/src/hooks/useOpenUnsafeLink.tsx
  packages/gui/src/locales/ar-SA/messages.po
  packages/gui/src/locales/be-BY/messages.po
  packages/gui/src/locales/bg-BG/messages.po
  packages/gui/src/locales/ca-ES/messages.po
  packages/gui/src/locales/cs-CZ/messages.po
  packages/gui/src/locales/da-DK/messages.po
  packages/gui/src/locales/de-DE/messages.po
  packages/gui/src/locales/el-GR/messages.po
  packages/gui/src/locales/en-AU/messages.po
  packages/gui/src/locales/en-NZ/messages.po
  packages/gui/src/locales/en-PT/messages.po
  packages/gui/src/locales/en-US/messages.po
  packages/gui/src/locales/es-AR/messages.po
  packages/gui/src/locales/es-ES/messages.po
  packages/gui/src/locales/es-MX/messages.po
  packages/gui/src/locales/fa-IR/messages.po
  packages/gui/src/locales/fi-FI/messages.po
  packages/gui/src/locales/fr-FR/messages.po
  packages/gui/src/locales/hr-HR/messages.po
  packages/gui/src/locales/hu-HU/messages.po
  packages/gui/src/locales/id-ID/messages.po
  packages/gui/src/locales/it-IT/messages.po
  packages/gui/src/locales/ja-JP/messages.po
  packages/gui/src/locales/ko-KR/messages.po
  packages/gui/src/locales/nl-NL/messages.po
  packages/gui/src/locales/no-NO/messages.po
  packages/gui/src/locales/pl-PL/messages.po
  packages/gui/src/locales/pt-BR/messages.po
  packages/gui/src/locales/pt-PT/messages.po
  packages/gui/src/locales/ro-RO/messages.po
  packages/gui/src/locales/ru-RU/messages.po
  packages/gui/src/locales/sk-SK/messages.po
  packages/gui/src/locales/sq-AL/messages.po
  packages/gui/src/locales/sr-SP/messages.po
  packages/gui/src/locales/sv-SE/messages.po
  packages/gui/src/locales/tr-TR/messages.po
  packages/gui/src/locales/uk-UA/messages.po
  packages/gui/src/locales/zh-CN/messages.po
  packages/gui/src/locales/zh-TW/messages.po
Labels: Fixed

#2504 checkpoint: into main from release/2.4.4 @ 7e6f90ed1bbda7dcc9181a7b424a82e4fb473901
  packages/gui/src/hooks/useOpenUnsafeLink.tsx
  packages/gui/src/locales/ar-SA/messages.po
  packages/gui/src/locales/be-BY/messages.po
  packages/gui/src/locales/bg-BG/messages.po
  packages/gui/src/locales/ca-ES/messages.po
  packages/gui/src/locales/cs-CZ/messages.po
  packages/gui/src/locales/da-DK/messages.po
  packages/gui/src/locales/de-DE/messages.po
  packages/gui/src/locales/el-GR/messages.po
  packages/gui/src/locales/en-AU/messages.po
  packages/gui/src/locales/en-NZ/messages.po
  packages/gui/src/locales/en-PT/messages.po
  packages/gui/src/locales/en-US/messages.po
  packages/gui/src/locales/es-AR/messages.po
  packages/gui/src/locales/es-ES/messages.po
  packages/gui/src/locales/es-MX/messages.po
  packages/gui/src/locales/fa-IR/messages.po
  packages/gui/src/locales/fi-FI/messages.po
  packages/gui/src/locales/fr-FR/messages.po
  packages/gui/src/locales/hr-HR/messages.po
  packages/gui/src/locales/hu-HU/messages.po
  packages/gui/src/locales/id-ID/messages.po
  packages/gui/src/locales/it-IT/messages.po
  packages/gui/src/locales/ja-JP/messages.po
  packages/gui/src/locales/ko-KR/messages.po
  packages/gui/src/locales/nl-NL/messages.po
  packages/gui/src/locales/no-NO/messages.po
  packages/gui/src/locales/pl-PL/messages.po
  packages/gui/src/locales/pt-BR/messages.po
  packages/gui/src/locales/pt-PT/messages.po
  packages/gui/src/locales/ro-RO/messages.po
  packages/gui/src/locales/ru-RU/messages.po
  packages/gui/src/locales/sk-SK/messages.po
  packages/gui/src/locales/sq-AL/messages.po
  packages/gui/src/locales/sr-SP/messages.po
  packages/gui/src/locales/sv-SE/messages.po
  packages/gui/src/locales/tr-TR/messages.po
  packages/gui/src/locales/uk-UA/messages.po
  packages/gui/src/locales/zh-CN/messages.po
  packages/gui/src/locales/zh-TW/messages.po
Labels: Changed, checkpoint_merge

#2522 npm audit fix
  package-lock.json
Labels: dependencies, Fixed
