Repository Chia-Network/chia-blockchain-gui, pull requests merged in 2024-02, with the labels that each got.

#2269 Electron not closing on Ubuntu
  packages/gui/src/util/chiaEnvironment.js
Labels: Fixed

#2273 checkpoint: into main from release/2.2.0 @ b8dbb83ee055adf8261999c110b7f499b01ec583
  packages/gui/src/components/plot/overview/PlotOverviewPlots.tsx
Labels: Changed, checkpoint_merge

#2274 Update follow-redirects, socks and ip
  package-lock.json
Labels: Changed

#2281 checkpoint: into main from release/2.2.0 @ abb10ab4405dc0f845b912c690594458284ae21e
  packages/gui/src/util/chiaEnvironment.js
Labels: Changed, checkpoint_merge

#2286 checkpoint: into main from release/2.2.0 @ bda1eabbbe9916685a78b31547547a14ada99aad
  packages/gui/src/util/chiaEnvironment.js
Labels: Changed, checkpoint_merge
