Repository Chia-Network/chia-blockchain-gui, pull requests merged in 2025-01, with the labels that each got.

#2526 Remove unused code that attempts to read the output of the daemon
  packages/gui/src/util/chiaEnvironment.js
Labels: stale-pr

#2564 Fixed losing focus issue on offer builder page
  packages/gui/src/components/offers2/OfferBuilderValue.tsx
Labels: Fixed

#2576 npm audit fix
  package-lock.json
Labels: dependencies, Fixed

#2589 checkpoint: into main from release/2.5.1 @ dfa616036c3224839f3eb9322e833feb94032f58
  package-lock.json
  package.json
  packages/api-react/package.json
  packages/api/package.json
  packages/core/package.json
  packages/gui/package.json
  packages/icons/package.json
  packages/wallets/package.json
Labels: Changed, checkpoint_merge

#2591 checkpoint: into main from release/2.5.1 @ 06551f55dbcfc3ad874efe9b6ac4321bb7747e1b
  package-lock.json
  package.json
Labels: Changed, checkpoint_merge

#2593 checkpoint: into main from release/2.5.1 @ d87eaffe3219ee3f9b6f7d28190d5f320e982e05
  package-lock.json
  package.json
Labels: Changed, checkpoint_merge

#2594 checkpoint: into main from release/2.5.1 @ 74c0f2eaea84c586e7bf5caa3f9f570d294dd3bc
  package-lock.json
  packages/gui/package.json
Labels: Changed, checkpoint_merge

#2596 checkpoint: into main from release/2.5.1 @ 342c856da71e6c0c08a76464c888950e1fa4f21f
  package-lock.json
Labels: Changed, checkpoint_merge

#2597 checkpoint: into main from release/2.5.1 @ a3b94b23a6963238bffe8fce251f4dd4cc1819cc
  packages/gui/src/components/app/AppRouter.tsx
  packages/gui/src/components/chiatools/ChiaToolsPage.tsx
  packages/gui/src/components/chiatools/logViewer/LogRecord.tsx
  packages/gui/src/components/chiatools/logViewer/LogViewer.tsx
  packages/gui/src/components/chiatools/logViewer/LogViewerCard.tsx
  packages/gui/src/components/chiatools/logViewer/LogViewerToolbar.tsx
  packages/gui/src/components/chiatools/logViewer/LogViewerTypes.ts
  packages/gui/src/components/chiatools/logViewer/LogViewerUtils.tsx
  packages/gui/src/components/dashboard/DashboardSideBar.tsx
  packages/gui/src/electron/main.tsx
  packages/gui/src/electron/preload.js
Labels: Changed, checkpoint_merge
